config/routes.rb
Rails.application.routes.draw do
  resources :bixi2s
  resources :bixis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :geocoder
  root "bixis#index"
end

app/models/.rb
class Bixi2 < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bixi.rb
class Bixi < ApplicationRecord  
  # État des stations BIXI au format XML ### on utilise XML car le lien pour le format json était brisé lors de la création de l'application -- PIERREV
  # URL: https://montreal.bixi.com/data/bikeStations.xml
  # station_id: identifiant unique de la station (is named "id" in bikeStations.xml, RENAMED to prevent conflict in database)
  # name: Nom de la station
  # terminalName: identifiant du terminal de la station
  # lastCommWithServer: horodatage de la dernière communication avec le serveur en nombres de millisecondes depuis le 1 janvier 1970.
  # lat: latitude de la station selon le référentiel géodésique WGS84
  # long: longitude de la station selon le référentiel géodésique WGS84
  # installed: valeur booléenne (true ou false) spécifiant si la station est installée.
  # locked: valeur booléenne (true ou false) spécifiant si la station est temporairement désactivée.
  # installDate: date d'installation
  # removalDate: date de retrait
  # temporary: valeur booléenne (true ou false) spécifiant s'il s'agit d'une station temporaire.
  # public: valeur booléenne (true ou false) spécifiant si l'enregistrement est public.
  # nbBikes: Nombre de vélos disponibles à cette station
  # nbEmptyDocks: Nombre de bornes disponibles pour accueillir des vélos
  # lastUpdateTime: horodatage de la dernière mise à jour des données en nombres de millisecondes depuis le 1 janvier 1970.

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, if: ->(obj){ not obj.address.present? or obj.address_changed? }  # auto-fetch address and prevent unnecessary recalculation


  def self.update_bike_stations_status
    require 'net/http' 
    xml_content = Net::HTTP.get(URI.parse(BIKE_STATIONS_URL))
    data = Hash.from_xml(xml_content)    
    ##### for efficiency, data must be persisted (We should not parse all stations at each HTTP call)
    if closest_available_bike.nil?
      # if database is empty, initialize it... this may take some time....
      update_bixis(data['stations']['station'])
      return
    end    
    last_update = Time.at(data['stations']['LastUpdate'].to_f/1000).utc
    bike_updated_at = closest_available_bike.updated_at
    if last_update > bike_updated_at
      update_bixis(data['stations']['station'])
    end     
  end
  

  def self.update_bixis(stations)
    stations.each do |station|
      self.connection
      bixi_station = self.find_or_initialize_by(terminalName: station['terminalName'])
      bixi_station.update_attributes(
      :station_id => station["id"],
      :name => station["name"],
      :distance => distance_from_fxinnovation(station["lat"], station["long"]),
      :terminalName => station["terminalName"],
      :lastCommWithServer => station["lastCommWithServer"],
      :latitude => station["lat"],
      :longitude => station["long"],
      :installed => station["installed"],
      :locked => station["locked"],
      :installDate => station["installDate"],
      :removalDate => station["removalDate"],
      :temporary => station["temporary"],
      :public => station["public"],
      :nbBikes => station["nbBikes"],
      :nbEmptyDocks => station["nbEmptyDocks"],
      :lastUpdateTime => station["lastUpdateTime"],
      :updated_at => Time.now
      )
    end
  end


  def self.closest_available_bike
    self.all.order(:distance).first    
  end
  
     
  def self.distance_from_fxinnovation(latitude, longitude)    
    Geocoder::Calculations.distance_between([latitude, longitude], [ORIGIN_LATITUDE,ORIGIN_LONGITUDE], {:units => :km})
  end
  
  
  def self.search(distance_min, distance_max)
    if distance_min and distance_max
      where('distance BETWEEN ? AND ?', distance_min, distance_max)
    else
      order('id DESC') 
    end
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  def index
    puts "test in index"
  end


end

app/controllers/bixis_controller.rb
class BixisController < ApplicationController
  before_action :set_bixi, only: [:show, :edit, :update, :destroy]

  # GET /bixis
  # GET /bixis.json
  def index
    Bixi.update_bike_stations_status
    @closest_bike_station = Bixi.closest_available_bike

    if params[:distance_min] and params[:distance_max]
      if params[:distance_min].empty? or params[:distance_max].empty?
        @bixis = Bixi.all.order(:distance) 
      else
        @bixis = Bixi.search(params[:distance_min], params[:distance_max]).order(:distance)
      end
    else
      @bixis = Bixi.all.order(:distance) 
    end  
  end

  # GET /bixis/1
  # GET /bixis/1.json
  def show
  end

  # GET /bixis/new
  def new
    @bixi = Bixi.new
  end

  # GET /bixis/1/edit
  def edit
  end

  # POST /bixis
  # POST /bixis.json
  def create
    @bixi = Bixi.new(bixi_params)

    respond_to do |format|
      if @bixi.save
        format.html { redirect_to @bixi, notice: 'Bixi was successfully created.' }
        format.json { render :show, status: :created, location: @bixi }
      else
        format.html { render :new }
        format.json { render json: @bixi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bixis/1
  # PATCH/PUT /bixis/1.json
  def update
    respond_to do |format|
      if @bixi.update(bixi_params)
        format.html { redirect_to @bixi, notice: 'Bixi was successfully updated.' }
        format.json { render :show, status: :ok, location: @bixi }
      else
        format.html { render :edit }
        format.json { render json: @bixi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bixis/1
  # DELETE /bixis/1.json
  def destroy
    @bixi.destroy
    respond_to do |format|
      format.html { redirect_to bixis_url, notice: 'Bixi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bixi
      @bixi = Bixi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bixi_params
      params.require(:bixi).permit(:station_id, :name, :distance, :address, :terminalName, :lastCommWithServer, :lat, :long, :installed, :locked, :installDate, :removalDate, :temporary, :public, :nbBikes, :nbEmptyDocks, :lastUpdateTime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bixis_helper.rb
module BixisHelper
end

app/views/bixis/_form.html.erb
<%= form_with(model: bixi, local: true) do |form| %>
  <% if bixi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bixi.errors.count, "error") %> prohibited this bixi from being saved:</h2>

      <ul>
      <% bixi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :station_id %>
    <%= form.number_field :station_id, id: :bixi_station_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bixi_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :bixi_address %>
  </div>
  <div class="field">
    <%= form.label :terminalName %>
    <%= form.number_field :terminalName, id: :bixi_terminalName %>
  </div>

  <div class="field">
    <%= form.label :lastCommWithServer %>
    <%= form.date_select :lastCommWithServer, id: :bixi_lastCommWithServer %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :bixi_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :bixi_longitude %>
  </div>

  <div class="field">
    <%= form.label :installed %>
    <%= form.check_box :installed, id: :bixi_installed %>
  </div>

  <div class="field">
    <%= form.label :locked %>
    <%= form.check_box :locked, id: :bixi_locked %>
  </div>

  <div class="field">
    <%= form.label :installDate %>
    <%= form.date_select :installDate, id: :bixi_installDate %>
  </div>

  <div class="field">
    <%= form.label :removalDate %>
    <%= form.date_select :removalDate, id: :bixi_removalDate %>
  </div>

  <div class="field">
    <%= form.label :temporary %>
    <%= form.check_box :temporary, id: :bixi_temporary %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :bixi_public %>
  </div>

  <div class="field">
    <%= form.label :nbBikes %>
    <%= form.number_field :nbBikes, id: :bixi_nbBikes %>
  </div>

  <div class="field">
    <%= form.label :nbEmptyDocks %>
    <%= form.number_field :nbEmptyDocks, id: :bixi_nbEmptyDocks %>
  </div>

  <div class="field">
    <%= form.label :lastUpdateTime %>
    <%= form.date_select :lastUpdateTime, id: :bixi_lastUpdateTime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bixis/edit.html.erb
<h1>Editing Bixi</h1>

<%= render 'form', bixi: @bixi %>

<%= link_to 'Show', @bixi %> |
<%= link_to 'Back', bixis_path %>

app/views/bixis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bixi Finder</h1>
<hr/>
<h4>ORIGIN location: <%= ORIGIN_LATITUDE %>,<%= ORIGIN_LONGITUDE %></h4>
<p><%= Geocoder.search("#{ORIGIN_LATITUDE},#{ORIGIN_LONGITUDE}").first.address %></p>

<% if not @closest_bike_station.nil? %>
	<h4>NEAREST AVAILABLE BIKE:</h4>
	<p> Station Name: <%= @closest_bike_station.name %></p>
	<p> Available Bikes: <%= @closest_bike_station.nbBikes %></p>
	<p> Distance: <%= @closest_bike_station.distance.round(3) %> km.</p>
	<p> Address:  <%= @closest_bike_station.address %></p>
	<p> Last Update:  <%= @closest_bike_station.updated_at.to_s %></p>
<% end %>

<hr/>
<h4>Search Bixi stations by distances in kilometers between:</h4> 
<%= form_tag(bixis_path, method: :get) do %>
  <%= text_field_tag :distance_min, params[:distance_min], :width => 10 %> and 
  <%= text_field_tag :distance_max, params[:distance_max] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
Note: distances are rounded to the nearest 3 decimal point,<br/>
and sorted by closest proximity first.<br/><br/>

<% if @bixis.blank? %>
  <h4>No result found</h4>
<% else %>
<table>
  <thead>
    <tr align="left">
      <!-- <th>Station</th> -->
      <th>Station Name</th>
      <th style="width:150px">Available Bikes</th>
      <th style="width:150px">Distance (km)</th>
      <!-- <th>Address</th> -->
      <!-- <th>Nbemptydocks</th> -->
      <!-- <th>Terminalname</th> -->
      <!-- <th>Latitude</th> -->
      <!-- <th>Longitude</th> -->
      <!-- <th>Installed</th> -->
      <!-- <th>Locked</th> -->
      <!-- <th>Lastcommwithserver</th> -->
      <!-- <th>Installdate</th> -->
      <!-- <th>Removaldate</th> -->
      <!-- <th>Temporary</th> -->
      <!-- <th>Public</th> -->
      <!-- <th>Lastupdatetime</th> -->
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @bixis.each do |bixi| %>
      <tr>
        <!-- <td><%= bixi.station_id %></td> -->
        <td><%= bixi.name %></td>
        <td><%= bixi.nbBikes %></td>
        <td><%= '%.3f' % bixi.distance.round(3) %></td>
        <!-- <td><%= bixi.address %></td> -->
        <!-- <td><%= bixi.nbEmptyDocks %></td> -->
        <!-- <td><%= bixi.terminalName %></td> -->
        <!-- <td><%= bixi.latitude %></td> -->
        <!-- <td><%= bixi.longitude %></td> -->
        <!-- <td><%= bixi.installed %></td> -->
        <!-- <td><%= bixi.locked %></td> -->
        <!-- <td><%= bixi.lastCommWithServer %></td> -->
        <!-- <td><%= bixi.installDate %></td> -->
        <!-- <td><%= bixi.removalDate %></td> -->
        <!-- <td><%= bixi.temporary %></td> -->
        <!-- <td><%= bixi.public %></td> -->
        <!-- <td><%= bixi.lastUpdateTime %></td> -->
        <!-- <td><%#= link_to 'Show', bixi %></td>
        <td><%#= link_to 'Edit', edit_bixi_path(bixi) %></td>
        <td><%#= link_to 'Destroy', bixi, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<br>

<% end %>
<%#= link_to 'New Bixi', new_bixi_path %>

app/views/bixis/new.html.erb
<h1>New Bixi</h1>

<%= render 'form', bixi: @bixi %>

<%= link_to 'Back', bixis_path %>

app/views/bixis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @bixi.station_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @bixi.name %>
</p>

<p>
  <strong>Terminalname:</strong>
  <%= @bixi.terminalName %>
</p>

<p>
  <strong>Lastcommwithserver:</strong>
  <%= @bixi.lastCommWithServer %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @bixi.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @bixi.longitude %>
</p>

<p>
  <strong>Installed:</strong>
  <%= @bixi.installed %>
</p>

<p>
  <strong>Locked:</strong>
  <%= @bixi.locked %>
</p>

<p>
  <strong>Installdate:</strong>
  <%= @bixi.installDate %>
</p>

<p>
  <strong>Removaldate:</strong>
  <%= @bixi.removalDate %>
</p>

<p>
  <strong>Temporary:</strong>
  <%= @bixi.temporary %>
</p>

<p>
  <strong>Public:</strong>
  <%= @bixi.public %>
</p>

<p>
  <strong>Nbbikes:</strong>
  <%= @bixi.nbBikes %>
</p>

<p>
  <strong>Nbemptydocks:</strong>
  <%= @bixi.nbEmptyDocks %>
</p>

<p>
  <strong>Lastupdatetime:</strong>
  <%= @bixi.lastUpdateTime %>
</p>

<%= link_to 'Edit', edit_bixi_path(@bixi) %> |
<%= link_to 'Back', bixis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bixifinder 
</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>